apiVersion: v1
kind: Service
metadata:
  name: content-distribution-service-service
spec:
  selector:
    app: content-distribution-service
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 80
      name: http
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
  type: LoadBalancer