apiVersion: v1
kind: Service
metadata:
  name: content-distribution-service-service
spec:
  selector:
    app: content-distribution-service
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 80
  type: LoadBalancer
