apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-storage
          mountPath: /usr/share/nginx/html
          
      - name: content-handler
        image: jkoivist20/edge-content-handler:latest
        ports:
        - containerPort: 8000  # metrics
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        volumeMounts:
        - name: shared-storage
          mountPath: /app/videos
          
      volumes:
      - name: shared-storage
        emptyDir: {}

apiVersion: v1
kind: Service
metadata:
  name: edge-server-service
spec:
  selector:
    app: edge-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: metrics
  type: LoadBalancer