apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-server
  template:
    metadata:
      labels:
        app: edge-server
    spec:
      containers:
      
      - name: video-server
        image: jkoivist20/edge-video-server:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-storage
          mountPath: /app/videos
          
      - name: content-handler
        image: jkoivist20/edge-content-handler:latest
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        volumeMounts:
        - name: shared-storage
          mountPath: /app/videos
          
      - name: frontend-builder
        image: jkoivist20/edge-frontend-builder:latest
        env:
        - name: MONGO_SERVICE
          value: "mongodb://mongodb-service:27017/"
        - name: SLEEP_INTERVAL
          value: "10"
        volumeMounts:
        - name: shared-storage
          mountPath: /app/videos
          
      volumes:
      - name: shared-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: edge-server-service
spec:
  selector:
    app: edge-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
